// lib/wishes/registry.ts
// Single source of truth for every wish shown on Home / All Wishes / Details.
// `enabled: false` means the details page still renders (checklist, cover,
// buttons) but Demo/Create buttons show "Coming Soon" instead of a 404 —
// this alone fixes the not-found bug for the 13 unimplemented wishes.

import { WishMeta } from "./types";

export const wishRegistry: WishMeta[] = [
  {
    slug: "proposal",
    title: "Proposal",
    emoji: "💍",
    shortDescription: "A cinematic romantic journey ending in your own proposal question.",
    coverImage: "/covers/proposal.jpg",
    cardAccent: { gradientFrom: "#3a0d16", gradientTo: "#1a0508", glowColor: "#d4af37" },
    checklist: [
      "Cinematic Romantic Opening",
      "Personal Message Journey",
      "Memory Moments",
      "Feelings / Reasons",
      "Private Letter",
      "Future Thoughts",
      "Emotional Build-Up",
      "Luxury Ring Box Reveal",
      "Custom Proposal Question",
      "Final Celebration",
    ],
    isFeatured: true,
    enabled: true,
  },
  {
    slug: "girlfriend-special",
    title: "Girlfriend Special",
    emoji: "🌹",
    shortDescription: "A glowing, heartfelt experience celebrating her, your way.",
    coverImage: "/covers/girlfriend-special.jpg",
    cardAccent: { gradientFrom: "#4a1030", gradientTo: "#1a0512", glowColor: "#ff6fa5" },
    checklist: [
      "Glowing Heart Opening",
      "Relationship Counter",
      "Polaroid Memories",
      "Reasons I Love You",
      "Little Things You Do",
      "Secret Notes",
      "Wax-Sealed Love Letter",
      "Promises",
      "Future Dreams",
      "Final Surprise",
    ],
    isFeatured: true,
    enabled: true,
  },
  {
    slug: "boyfriend-special",
    title: "Boyfriend Special",
    emoji: "🖤",
    shortDescription: "A cinematic tribute to everything you appreciate about him.",
    coverImage: "/covers/boyfriend-special.jpg",
    cardAccent: { gradientFrom: "#0d1730", gradientTo: "#05070f", glowColor: "#6f9bff" },
    checklist: [
      "Cinematic Opening",
      "Things I Never Say Enough",
      "Favourite Memories",
      "What I Admire About You",
      "Inside Joke / Cute Moment",
      "Private Letter",
      "Thank You For...",
      "Future Plans",
      "Final Appreciation",
    ],
    enabled: false,
  },
  {
    slug: "long-distance-love",
    title: "Long Distance Love",
    emoji: "💞",
    shortDescription: "Two places, one connection — a journey that brings you together.",
    coverImage: "/covers/long-distance-love.jpg",
    cardAccent: { gradientFrom: "#0a1128", gradientTo: "#05070f", glowColor: "#8fd6ff" },
    checklist: [
      "Two Names, Two Locations",
      "Distance Connection Animation",
      "Relationship Counter",
      "Memories",
      "Things I Miss About You",
      "Private Letter",
      "Next Meeting Countdown",
      "Future Reunion",
      "Final Connection",
    ],
    enabled: false,
  },
  {
    slug: "anniversary",
    title: "Anniversary",
    emoji: "❤️",
    shortDescription: "Celebrate your journey together with a golden keepsake moment.",
    coverImage: "/covers/anniversary.jpg",
    cardAccent: { gradientFrom: "#3a1a0d", gradientTo: "#1a0a05", glowColor: "#e8c27a" },
    checklist: [
      "Anniversary Opening",
      "Together For... Counter",
      "How It Started",
      "Relationship Timeline",
      "Milestones",
      "Then vs Now Photos",
      "Love Letter",
      "What I Still Love About You",
      "Future Together",
    ],
    enabled: false,
  },
  {
    slug: "love-letter",
    title: "Love Letter",
    emoji: "💌",
    shortDescription: "A sealed letter experience built around your own words.",
    coverImage: "/covers/love-letter.jpg",
    cardAccent: { gradientFrom: "#2c1808", gradientTo: "#150c04", glowColor: "#e0a84c" },
    checklist: [
      "Sealed Envelope",
      "Wax Seal Break",
      "Letter Unfolds",
      "Optional Photos Between Sections",
      "Mini Notes",
      "Signature",
      "Hidden P.S. Surprise",
    ],
    enabled: false,
  },
  {
    slug: "love-confession",
    title: "I Love You / Love Confession",
    emoji: "💕",
    shortDescription: "Build up to the moment you finally say it.",
    coverImage: "/covers/love-confession.jpg",
    cardAccent: { gradientFrom: "#33101f", gradientTo: "#17050c", glowColor: "#ff5c8a" },
    checklist: ["Heartbeat Opening", "Gradual Reveal", "The Confession", "Final Message"],
    enabled: false,
  },
  {
    slug: "miss-you",
    title: "Miss You",
    emoji: "☁️",
    shortDescription: "A soft, rainy-window ode to someone you're missing.",
    coverImage: "/covers/miss-you.jpg",
    cardAccent: { gradientFrom: "#101828", gradientTo: "#070b12", glowColor: "#9fb8d9" },
    checklist: ["Rain & Moonlight Opening", "Things I Miss", "Memories", "Final Message"],
    enabled: false,
  },
  {
    slug: "sorry",
    title: "Sorry",
    emoji: "🥺",
    shortDescription: "A gentle, honest apology experience.",
    coverImage: "/covers/sorry.jpg",
    cardAccent: { gradientFrom: "#1c1c2e", gradientTo: "#0c0c14", glowColor: "#b8a6ff" },
    checklist: ["Honest Opening", "What I'm Sorry For", "How I'll Do Better", "Final Message"],
    enabled: false,
  },
  {
    slug: "birthday-surprise",
    title: "Birthday Surprise",
    emoji: "🎂",
    shortDescription: "Warm celebration lighting, cake, balloons, and your birthday wishes.",
    coverImage: "/covers/birthday-surprise.jpg",
    cardAccent: { gradientFrom: "#3a1030", gradientTo: "#180614", glowColor: "#ffb84c" },
    checklist: [
      "Celebration Opening",
      "Age / Birthday Counter (optional)",
      "Photos",
      "Birthday Messages",
      "Special Memories",
      "Birthday Letter",
      "Final Message",
    ],
    isPopular: true,
    enabled: false,
  },
  {
    slug: "congratulations",
    title: "Congratulations",
    emoji: "🎓",
    shortDescription: "Celebrate an achievement with a personal, festive experience.",
    coverImage: "/covers/congratulations.jpg",
    cardAccent: { gradientFrom: "#0d2a1c", gradientTo: "#04140c", glowColor: "#6fe0a8" },
    checklist: ["Opening", "The Achievement", "Why It Matters", "Final Message"],
    enabled: false,
  },
  {
    slug: "best-friend-special",
    title: "Best Friend Special",
    emoji: "👑",
    shortDescription: "A fun, heartfelt tribute to your ride-or-die.",
    coverImage: "/covers/best-friend-special.jpg",
    cardAccent: { gradientFrom: "#2a1a3a", gradientTo: "#140a1c", glowColor: "#c58aff" },
    checklist: ["Opening", "Memories", "Inside Jokes", "Why You're the Best", "Final Message"],
    enabled: false,
  },
  {
    slug: "countdown-until-we-meet",
    title: "Countdown Until We Meet",
    emoji: "📅",
    shortDescription: "A live countdown to your next meeting, wrapped in anticipation.",
    coverImage: "/covers/countdown-until-we-meet.jpg",
    cardAccent: { gradientFrom: "#0d1c30", gradientTo: "#050a14", glowColor: "#7ab8ff" },
    checklist: ["Opening", "Countdown", "Things We'll Do", "Final Message"],
    enabled: false,
  },
  {
    slug: "good-morning",
    title: "Good Morning",
    emoji: "🌞",
    shortDescription: "A sunrise-lit good morning made just for them.",
    coverImage: "/covers/good-morning.jpg",
    cardAccent: { gradientFrom: "#3a2a0d", gradientTo: "#1a1204", glowColor: "#ffd166" },
    checklist: ["Sunrise Opening", "Morning Message", "Final Message"],
    enabled: false,
  },
  {
    slug: "good-night",
    title: "Good Night",
    emoji: "🌙",
    shortDescription: "A moonlit, starry good night message.",
    coverImage: "/covers/good-night.jpg",
    cardAccent: { gradientFrom: "#0a0e28", gradientTo: "#040614", glowColor: "#9db4ff" },
    checklist: ["Moonlit Opening", "Night Message", "Final Message"],
    enabled: false,
  },
];

export function getWishMeta(slug: string): WishMeta | undefined {
  return wishRegistry.find((w) => w.slug === slug);
}
