const base={statusMessages:["Preparing something special…","Gathering your memories…","Finding the right words…","Almost ready…"],memoryCaptions:["A memory worth keeping","A moment I never want to forget","A little piece of us","A beautiful moment"],particles:["♥","✦","❋"]};
const make=(id,title,category,icon,desc,example,theme,finalTitle,openIntro,letterHeading="FROM THE HEART")=>({...base,id,title,category,icon,art:`art-${id}`,desc,example,formHint:"Write a message that feels like your heart speaking.",kicker:"MADE JUST FOR YOU",openIntro,letterHeading,finalTitle});
export const cards=[
  make("proposal","Proposal","Love","\ud83d\udc8d","A beautiful question deserves a beautiful moment.","I have something important to ask you\u2026 Will you be my forever? \u2764\ufe0f","proposal","Will You Be My Forever?","There is something I need to ask you\u2026"),
  make("girlfriend","Girlfriend Special","Love","\ud83c\udf39","A romantic surprise for your favourite girl.","You make my world softer, brighter and more beautiful. I am so lucky to have you. \u2764\ufe0f","girlfriend","You Mean the World to Me","A little celebration of us\u2026"),
  make("boyfriend","Boyfriend Special","Love","\ud83d\udda4","A thoughtful surprise made especially for him.","You are my favourite person, my safe place and my forever teammate. I love you. \ud83d\udda4","boyfriend","My Favourite Person","This little surprise is just for you\u2026"),
  make("long-distance","Long Distance Love","Love","\ud83d\udc9e","A warm reminder that distance cannot change love.","Miles may be between us, but you are always close to my heart. I cannot wait to hold you again. \ud83d\udc9e","long-distance","No Distance Can Change Us","Even from far away, this is for you\u2026"),
  make("anniversary","Anniversary","Love","\u2764\ufe0f","Celebrate the love, memories and time you share.","Another year with you is another year of my favourite memories. Happy Anniversary, my love. \u2764\ufe0f","anniversary","Still Choosing You","A little celebration of our journey\u2026"),
  make("love-letter","Love Letter","Love","\ud83d\udc8c","A timeless letter for someone who means everything.","If I could write every reason I love you, this letter would never end. You are so special to me. \ud83d\udc8c","love-letter","A Letter From My Heart","There are a few things I need you to know\u2026"),
  make("love-confession","Love Confession","Love","\ud83d\udc95","A sweet way to finally say what your heart feels.","I have been keeping this in my heart for a while\u2026 I like you more than words can explain. \ud83d\udc95","love-confession","I Have Something to Confess","I have been wanting to say this\u2026"),
  make("miss","Miss You","Emotion","\u2601\ufe0f","A soft memory journey for someone you wish was near.","I miss your voice, your smile and all the little moments we share. I wish you were here. \u2601\ufe0f","miss","I Miss You","There is something I wish you were here for\u2026"),
  make("sorry","Sorry","Emotion","\ud83e\udd7a","A gentle way to say what matters after a difficult moment.","I am truly sorry. You matter to me more than my pride, and I hope we can make things right. \ud83e\udd0d","sorry","I\u2019m Truly Sorry","There is something I need to say\u2026"),
  make("birthday","Birthday Surprise","Celebration","\ud83c\udf82","A joyful birthday surprise made just for them.","Happy Birthday! May this year bring you happiness, success, love and beautiful memories. You deserve the best. \ud83c\udf82\u2728","birthday","Happy Birthday","A little surprise for you\u2026"),
  make("best-friend","Best Friend Special","Friendship","\ud83d\udc51","A celebration of the friend who makes life better.","Thank you for being my constant, my laughter and my favourite person to call. You are one of a kind. \ud83d\udc51","best-friend","My Forever Friend","This is for the friend who means so much\u2026"),
  make("countdown","Countdown Until We Meet","Love","\ud83d\udcc5","Make the wait for your next meeting feel magical.","Every day brings us closer to the moment we meet again. I am counting every second. \ud83d\udcc5\u2764\ufe0f","countdown","Until We Meet Again","The countdown to our next moment begins\u2026"),
  make("good-morning","Good Morning","Daily","\ud83c\udf1e","Start someone\u2019s day with a little warmth and love.","Good morning, beautiful soul. I hope today brings you peace, smiles and everything you deserve. \ud83c\udf1e","good-morning","Good Morning, Sunshine","A little light for the start of your day\u2026"),
  make("good-night","Good Night","Daily","\ud83c\udf19","A peaceful good-night message to end the day.","Good night. Rest well, dream sweetly and remember that you are always in my heart. \ud83c\udf19","good-night","Sweet Dreams","Before you close your eyes\u2026"),
  make("raksha-bandhan","Raksha Bandhan","Family","\ud83c\udf38","A heartfelt celebration of the bond between siblings.","No matter how much we grow, you will always be my favourite partner in crime. Happy Raksha Bandhan. \ud83c\udf38","raksha-bandhan","Our Forever Bond","For a bond that only grows stronger\u2026"),
];
