import { WishTemplate, CustomizationStep, DemoData, WishExperienceConfig } from '@/types';

export const wishTemplates: WishTemplate[] = [
  {
    id: 'proposal',
    slug: 'proposal',
    title: 'Proposal',
    emoji: '💍',
    description: 'A cinematic romantic experience culminating in a luxury ring box reveal with your custom question.',
    coverImage: '/images/proposal-cover.jpg',
    theme: { primary: '#9f1239', secondary: '#fce7f3', background: '#1a0505', accent: '#fbbf24' },
    experienceFeatures: [
      'Cinematic Romantic Opening',
      'Personal Message Journey',
      'Memory Moments',
      'Feelings / Reasons',
      'Private Letter',
      'Future Thoughts',
      'Final Emotional Build-Up',
      'Luxury Ring Box Reveal',
      'Custom Proposal Question',
      'Final Celebration',
    ],
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'girlfriend-special',
    slug: 'girlfriend-special',
    title: 'Girlfriend Special',
    emoji: '🌹',
    description: 'A rose-tinted romantic journey with glowing hearts, polaroid memories, and a wax-sealed love letter.',
    coverImage: '/images/girlfriend-cover.jpg',
    theme: { primary: '#ec4899', secondary: '#fce7f3', background: '#1a0510', accent: '#f472b6' },
    experienceFeatures: [
      'Glowing Heart Opening',
      'Personal Greeting',
      'Relationship Counter',
      'Polaroid Memories',
      'Reasons I Love You',
      'Wax-Sealed Love Letter',
      'Promises & Dreams',
      'Final Glowing Heart Surprise',
    ],
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'boyfriend-special',
    slug: 'boyfriend-special',
    title: 'Boyfriend Special',
    emoji: '🖤',
    description: 'A deep cinematic experience with navy atmosphere, appreciation vault, and heartfelt moments.',
    coverImage: '/images/boyfriend-cover.jpg',
    theme: { primary: '#1e3a5f', secondary: '#dbeafe', background: '#0a0f1a', accent: '#60a5fa' },
    experienceFeatures: [
      'Cinematic Opening',
      'Things I Never Say Enough',
      'Favorite Memories',
      'What I Admire About You',
      'Private Letter',
      'Appreciation Vault Reveal',
    ],
    isFeatured: true,
  },
  {
    id: 'long-distance-love',
    slug: 'long-distance-love',
    title: 'Long Distance Love',
    emoji: '💞',
    description: 'Two distant lights connected across the night sky. A deeply emotional experience for lovers apart.',
    coverImage: '/images/long-distance-cover.jpg',
    theme: { primary: '#7c3aed', secondary: '#ede9fe', background: '#0f0520', accent: '#a78bfa' },
    experienceFeatures: [
      'Distance Connection Animation',
      'Relationship Counter',
      'Things I Miss About You',
      'Private Letter',
      'Next Meeting Countdown',
      'Hearts Connect Signature Moment',
    ],
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'anniversary',
    slug: 'anniversary',
    title: 'Anniversary',
    emoji: '❤️',
    description: 'Warm champagne gold celebration with relationship timeline and a premium memory keepsake.',
    coverImage: '/images/anniversary-cover.jpg',
    theme: { primary: '#b45309', secondary: '#fef3c7', background: '#1a1005', accent: '#fbbf24' },
    experienceFeatures: [
      'Anniversary Opening',
      'Together For Counter',
      'Relationship Timeline',
      'Then vs Now Photos',
      'Love Letter',
      'Memory Keepsake Reveal',
    ],
    isFeatured: true,
  },
  {
    id: 'love-letter',
    slug: 'love-letter',
    title: 'Love Letter',
    emoji: '💌',
    description: 'An elegant wax-sealed letter experience with a hidden P.S. surprise at the end.',
    coverImage: '/images/love-letter-cover.jpg',
    theme: { primary: '#dc2626', secondary: '#fee2e2', background: '#1a0505', accent: '#f87171' },
    experienceFeatures: [
      'Sealed Envelope Opening',
      'Wax Seal Break',
      'Elegant Letter Reveal',
      'Photos Between Sections',
      'Signature Moment',
      'Hidden P.S. Surprise',
    ],
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'love-confession',
    slug: 'love-confession',
    title: 'Love Confession',
    emoji: '💕',
    description: 'Build emotional tension as hidden message pieces come together to reveal your confession.',
    coverImage: '/images/love-confession-cover.jpg',
    theme: { primary: '#db2777', secondary: '#fce7f3', background: '#1a0510', accent: '#f472b6' },
    experienceFeatures: [
      'Emotional Build-Up',
      'Hidden Message Pieces',
      'Pieces Join Together',
      'Custom Confession Reveal',
    ],
    isPopular: true,
  },
  {
    id: 'miss-you',
    slug: 'miss-you',
    title: 'Miss You',
    emoji: '☁️',
    description: 'Rainy window atmosphere transitioning to moonlight with a virtual hug moment.',
    coverImage: '/images/miss-you-cover.jpg',
    theme: { primary: '#475569', secondary: '#e2e8f0', background: '#0a0f1a', accent: '#94a3b8' },
    experienceFeatures: [
      'Rainy Atmosphere',
      'Memory Window',
      'Things I Miss',
      'Unsent Notes',
      'Virtual Hug Moment',
      'Moonlight Transition',
    ],
    isPopular: true,
  },
  {
    id: 'sorry',
    slug: 'sorry',
    title: 'Sorry',
    emoji: '🥺',
    description: 'A sincere apology experience where a broken heart slowly reconnects and warms.',
    coverImage: '/images/sorry-cover.jpg',
    theme: { primary: '#4c1d95', secondary: '#ede9fe', background: '#0f051a', accent: '#8b5cf6' },
    experienceFeatures: [
      'Quiet Opening',
      'Personal Apology',
      'What I Regret',
      'Good Memories',
      'Apology Letter',
      'Broken Heart Reconnects',
    ],
  },
  {
    id: 'birthday-surprise',
    slug: 'birthday-surprise',
    title: 'Birthday Surprise',
    emoji: '🎂',
    description: 'A warm celebration with virtual cake, candles, make-a-wish moment, and confetti celebration.',
    coverImage: '/images/birthday-cover.jpg',
    theme: { primary: '#ea580c', secondary: '#ffedd5', background: '#1a0a05', accent: '#fb923c' },
    experienceFeatures: [
      'Mystery Gift Opening',
      'Birthday Greeting',
      'Virtual Birthday Cake',
      'Make A Wish Moment',
      'Confetti Celebration',
      'Birthday Letter',
    ],
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'congratulations',
    slug: 'congratulations',
    title: 'Congratulations',
    emoji: '🎓',
    description: 'Elegant gold and navy achievement celebration with a premium trophy reveal.',
    coverImage: '/images/congratulations-cover.jpg',
    theme: { primary: '#b45309', secondary: '#fef3c7', background: '#0a0f1a', accent: '#fbbf24' },
    experienceFeatures: [
      'Achievement Reveal',
      'Journey Timeline',
      'Proud Messages',
      'Achievement Badge',
      'Personal Letter',
      'Premium Trophy Reveal',
    ],
  },
  {
    id: 'best-friend-special',
    slug: 'best-friend-special',
    title: 'Best Friend Special',
    emoji: '👑',
    description: 'Fun, nostalgic, and emotional journey with polaroids, inside jokes, and a memory capsule.',
    coverImage: '/images/best-friend-cover.jpg',
    theme: { primary: '#0891b2', secondary: '#cffafe', background: '#051a1a', accent: '#22d3ee' },
    experienceFeatures: [
      'Fun Opening',
      'Friendship Counter',
      'Inside Jokes',
      'Best Memories',
      'Personal Letter',
      'Memory Capsule Reveal',
    ],
    isPopular: true,
  },
  {
    id: 'countdown-until-we-meet',
    slug: 'countdown-until-we-meet',
    title: 'Countdown Until We Meet',
    emoji: '📅',
    description: 'A live countdown experience that transforms into "Today\'s The Day!" when the timer reaches zero.',
    coverImage: '/images/countdown-cover.jpg',
    theme: { primary: '#059669', secondary: '#d1fae5', background: '#051a10', accent: '#34d399' },
    experienceFeatures: [
      'Live Countdown Timer',
      'Meeting Plans',
      'Memories',
      'Things We\'ll Do First',
      '"Today\'s The Day!" Transformation',
    ],
  },
  {
    id: 'good-morning',
    slug: 'good-morning',
    title: 'Good Morning',
    emoji: '🌞',
    description: 'An interactive sunrise experience that transforms darkness into a beautiful morning.',
    coverImage: '/images/good-morning-cover.jpg',
    theme: { primary: '#d97706', secondary: '#fef3c7', background: '#0a0f1a', accent: '#fbbf24' },
    experienceFeatures: [
      'Pre-Dawn Atmosphere',
      'Interactive Sunrise',
      'Morning Greeting',
      'Positive Message',
      'Final Morning Card',
    ],
  },
  {
    id: 'good-night',
    slug: 'good-night',
    title: 'Good Night',
    emoji: '🌙',
    description: 'A calming midnight experience where stars connect into a beautiful constellation.',
    coverImage: '/images/good-night-cover.jpg',
    theme: { primary: '#4338ca', secondary: '#e0e7ff', background: '#050a1a', accent: '#818cf8' },
    experienceFeatures: [
      'Sunset to Night Transition',
      'Calming Interactive Moment',
      'Twinkling Stars',
      'Interactive Constellation',
      'Final Message',
    ],
  },
];

export function getTemplateBySlug(slug: string): WishTemplate | undefined {
  return wishTemplates.find(t => t.slug === slug);
}

export function getTemplateById(id: string): WishTemplate | undefined {
  return wishTemplates.find(t => t.id === id);
}

export function getFeaturedWishes(): WishTemplate[] {
  return wishTemplates.filter(t => t.isFeatured);
}

export function getPopularWishes(): WishTemplate[] {
  return wishTemplates.filter(t => t.isPopular);
}

export function getNewWishes(): WishTemplate[] {
  return wishTemplates.filter(t => t.isNew);
}
